### PR TITLE
Fix crashing on casual

### PR DESCRIPTION
**Pull request by xbHA16ha11y**
Well, theres still a problem. Aimbot doesnt work, and triggerbot. I dont know how to fix it.

### CODE REVIEW

**Comment by canedoly** [comment]
why? just let this cheat die, there are better cheats available (jengaware, seownedde) where 1 of them has the source published

**Comment by xbHA16ha11y** [comment]
Jengaware doesnt even fucking have auto-shoot, Can you shut the fuck up?

**Comment by Loremaster312** [comment]
Seowned and Jengaware better than Fedoraware? 💀

**Comment by xbHA16ha11y** [comment]
bro doesnt know jengaware is based on fedware and fedware is based on seowned. You truly are dense

also jengaware's proj aimbot is broken so  ITS EVEN WORSER THAN SEOWNED LMAO
shut up.

**Comment by xxmyn** [comment]
can't recreate triggerbot and aimbot issues on my fork and im not downloading this one just to check but will merge because people use this.

**Comment by N1kolasFlaV** [comment]
> Jengaware doesnt even fucking have auto-shoot, Can you shut the fuck up?

Yes it does you retard

**Comment by xxmyn** [comment]
haha i cant block you but i can still hide ur comments get owned

**Comment by N1kolasFlaV** [comment]
> haha i cant block you but i can still hide ur comments get owned

Also fuck you

**Comment by Loremaster312** [comment]
XDDDD

**Comment by Loremaster312** [comment]
Seowned is a cheat that hasn't been updated for two years, Jengaware has stolen code and as you say it doesn't even have auto-shot. 

Fedoraware is better and has a better design

**Comment by xbHA16ha11y** [comment]
True

**Comment by xbHA16ha11y** [comment]
> 

Wait, so aimbot and triggerbot is still broken, am i right?

**Pull request merged**
